### ISSUE TITLE
Proxy Clients in Training

### ISSUE THREAD

**Issue by gwmdunda** [Liangqiong/ViT-FL-main#2]
I am confused why there is a notion of proxy clients and current selected clients in the train_FedAvg.py. Could you shed some light on this? Thank you

**Comment by Liangqiong** [comment]
Thanks for your interest in our work.

Since our FL environment is simulated on one computer, and storing the model weights for each client requires large memory and some times infeasible on one computer. 
For example, in our edge case study, around 60,000 clients are involved. In our implementation,  instead of storing the model weights of all the local clients, we just use several proxy clients to store the model weights. The number of proxy clients is set to the number of parallel training clients. 

Please let me know if you have further question regarding this.

**Comment by gwmdunda** [comment]
Thank you for your explanation!
